// Created by Crowbar 0.55

$include "F:\SMD_PROJECTS\PHUNBASE_SANDSTORM\unreal_scale.qci"

$modelname "weapons\upgrades\a_standard_m16a4.mdl"

$bodygroup "standard"
{
	studio "SKM_1P_M16A4_KACRailCover_1_Top.smd"
}

$surfaceprop "default"

$contents "solid"

// $illumposition 0 0 0 //$illumposition 0 6 0 //$illumposition 0 0 0 //$illumposition -2.321 -8.553 -1.402

$cdmaterials "models\weapons\ins2_sandstorm\"

$sequence "reference" {
	"SKM_1P_M16A4_KACRailCover_1_Top.smd"
}
