// Created by Crowbar 0.55

$include "..\..\..\unreal_scale.qci"

$modelname "weapons\upgrades\a_carryhandle_m16.mdl"

$bodygroup "standard"
{
	blank
	studio "SKM_1P_M16A2.smd"
}

$surfaceprop "default"

$contents "solid"

// $illumposition 0 0 0 //$illumposition 0 6 0 //$illumposition 0 0 0 //$illumposition -2.321 -8.553 -1.402

$cdmaterials "models\weapons\ins2_sandstorm\"

$bonemerge "A_Optic"

$sequence "reference" {
	"SKM_1P_M16A2.smd"
}
