// Created by Crowbar 0.55

// $include "F:\SMD_PROJECTS\PHUNBASE_SANDSTORM\unreal_scale.qci"
// $scale 0.393700787
// $scale 0.787401574
$scale 1.574803148

$modelname "weapons\upgrades\a_foregrip_sec.mdl"

$bodygroup "foregrip"
{
	studio "SKM_1P_A_FG_KAC.smd"
}


$surfaceprop "default"

$contents "solid"

$illumposition 0 0 0

$cdmaterials "models\weapons\ins2_sandstorm\"

$renamebone "b_attachment_root" "A_Foregrip"

$bonemerge "A_Foregrip"

$sequence "idle" {
	"SKM_1P_A_FG_KAC.smd"
}
