// Created by Crowbar 0.55

$modelname "weapons\upgrades\w_flipup3.mdl"

$bodygroup "standard"
{
	studio "SKM_1P_AUG_World_Sights.smd"
}

$surfaceprop "default"

$contents "solid"

// $illumposition 0 0 0 //$illumposition 0 6 0 //$illumposition 0 0 0 //$illumposition -2.321 -8.553 -1.402

$cdmaterials "models\weapons\ins2_sandstorm\"

$bonemerge "R Hand"

$sequence "reference" {
	"SKM_1P_AUG_World_Sights.smd"
}
