// Created by Crowbar 0.55

$include "F:\SMD_PROJECTS\PHUNBASE_SANDSTORM\unreal_scale.qci"

$modelname "weapons\upgrades\a_standard_mk18.mdl"

$bodygroup "sights_up"
{
	studio "SKM_1P_A_S_MK18Sight_Up.smd"
}

$surfaceprop "default"

$contents "solid"

// $illumposition 0 0 0 //$illumposition 0 6 0 //$illumposition 0 0 0 //$illumposition -2.321 -8.553 -1.402

$cdmaterials "models\weapons\ins2_sandstorm\"

$sequence "reference" {
	"SKM_1P_A_S_MK18Sight_Up.smd"
}
