// Created by Crowbar 0.55

$modelname "weapons\upgrades\a_modkit_mosin.mdl"

$include "F:\SMD_PROJECTS\PHUNBASE_SANDSTORM\unreal_scale.qci"

$bodygroup "rail"
{
	studio "SKM_1P_A_MosinRail.smd"
}

$surfaceprop "default"
$contents "solid"

$illumposition 0 0 0

$cdmaterials "models\weapons\upgrades\"
$cdmaterials "models\weapons\ins2_sandstorm\"

$sequence "standard_idle" {
	"SKM_1P_A_MosinRail.smd"
}



