// Created by Crowbar 0.55

$modelname "weapons\upgrades\w_modkit_6.mdl"

$bodygroup "rail"
{
	studio "F:\SMD_PROJECTS\PHUNBASE_SANDSTORM\release\upgrades\accessories\SKM_1P_A_AC_AKRail_World.smd"
}


$surfaceprop "default"

$contents "solid"

$illumposition 0 0 0

$cdmaterials "models\weapons\ins2_sandstorm\"

$bonemerge "ATTACH_ModKit"

$sequence "idle" {
	"F:\SMD_PROJECTS\PHUNBASE_SANDSTORM\release\upgrades\accessories\SKM_1P_A_AC_AKRail_World.smd"
}
