// Created by Crowbar 0.55

$include "..\..\..\unreal_scale.qci"

$modelname "weapons\upgrades\a_standard3_m16a4.mdl"

$bodygroup "weapon"
{
	blank
	studio "SKM_1P_Famas.dmx"
}

$surfaceprop "default"

$contents "solid"

// $illumposition 0 0 0 //$illumposition 0 6 0 //$illumposition 0 0 0 //$illumposition -2.321 -8.553 -1.402

$cdmaterials "models\weapons\ins2_sandstorm\"

$bonemerge "b_wpn"

$sequence "reference" {
	"SKM_1P_Famas.dmx"
}
