// Created by Crowbar 0.55

$modelname "gmod4phun\sandstorm\weapons\v_mk17.mdl"

$bodygroup "weapon"
{
	studio "SKM_1P_MK17.smd"
}

$surfaceprop "default"
$contents "solid"

$cdmaterials "gmod4phun\sandstorm\weapons\mk17\"
$cdmaterials "gmod4phun\sandstorm\weapons\"

$include "v_mk17_bones.qci"

$include "F:\SMD_PROJECTS\PHUNBASE_SANDSTORM\ins2_bones_follow_sandstorm.qci"

$sequence "reference" {
	"SKM_1P_MK17.smd"
}
