// Created by Crowbar 0.55

// $include "F:\SMD_PROJECTS\PHUNBASE_SANDSTORM\unreal_scale.qci"

$modelname "weapons\upgrades\w_standard_sterling.mdl"

$bodygroup "barrel"
{
	studio "SKM_1P_Uzi_World_BarrelStandard.smd"
}

$surfaceprop "default"
$contents "solid"

$illumposition 0 0 0

$cdmaterials "models\weapons\ins2_sandstorm\"

$bonemerge "WPN_Master"

$sequence "idle" {
	"SKM_1P_Uzi_World_BarrelStandard.smd"
}
