// Created by Crowbar 0.55

$modelname "weapons\upgrades\w_standard_aks74u.mdl"

$bodygroup "foregrip"
{
	blank
	studio "SKM_1P_AKAlpha_World_Foregrip.smd"
}


$surfaceprop "default"

$contents "solid"

$illumposition 0 0 0

$cdmaterials "models\weapons\ins2_sandstorm\"

$renamematerial "MI_1P_A_FG_Special" "MI_1P_A_FG_Special_BLK"

$bonemerge "R Hand"

$sequence "idle" {
	"SKM_1P_AKAlpha_World_Foregrip.smd"
}
